#!/bin/sh

# add more args here according to preference
ARGS="--volume=60"

notification(){
	notify-send "Now Playing:" "Lofi Radio ☕️🎶"
}

menu(){
	printf "1. Lofi Girl\n"
	printf "2. Chillhop\n"
	printf "3. Box Lofi\n"
	printf "4. The Bootleg Boy\n"
	printf "5. Radio Spinner\n"
	printf "6. SmoothChill"
}

main() {
	choice=$(menu | rofi -dmenu | cut -d. -f1)

	case $choice in
		1)
			notification ;
            URL="https://play.streamafrica.net/lofiradio"
			break
			;;
		2)
			notification ;
            URL="http://stream.zeno.fm/fyn8eh3h5f8uv"
			break
			;;
		3)
			notification ;
            URL="http://stream.zeno.fm/f3wvbbqmdg8uv"
			break
			;;
		4)
			notification ;
            URL="http://stream.zeno.fm/0r0xa792kwzuv"
			break
			;;
		5)
			notification ;
            URL="https://live.radiospinner.com/lofi-hip-hop-64"
			break
			;;
		6)
			notification ;
            URL="https://media-ssl.musicradio.com/SmoothChill"
			break
			;;
	esac
    # run mpv with args and selected url
    # added title arg to make sure the pkill command kills only this instance of mpv
    mpv $ARGS --title="radio-mpv" $URL
}

pkill -f radio-mpv || main
